# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: /mnt/bigdisk/data/datasets/gender-1M/train/ #/scratch/ilsvrc12/train_hkl_b256_b_256/
val_folder: /mnt/bigdisk/data/datasets/gender-1M/valid/ #/scratch/ilsvrc12/val_hkl_b256_b_256/
