import numpy as np
import pdb

# build the tree from the leaves
leaves = [
    'Women-Clothing-Beachwear',
    'Women-Clothing-Coats',
    'Women-Clothing-Dresses',
    'Women-Clothing-Hosiery',
    'Women-Clothing-Jackets',
    'Women-Clothing-Jeans',
    'Women-Clothing-Jumpsuits',
    'Women-Clothing-Knitwear',
    'Women-Clothing-Lingerie',
    'Women-Clothing-Nightwear',
    'Women-Clothing-Pants',
    'Women-Clothing-Shorts',
    'Women-Clothing-Skirts',
    'Women-Clothing-Suits',
    'Women-Clothing-Sweats',
    'Women-Clothing-Tops',
    'Women-Shoes-Boots',
    'Women-Shoes-Flats',
    'Women-Shoes-Heels',
    'Women-Shoes-Sneakers',
    'Women-Shoes-Wedges',
    'Women-Bags-Backpacks',
    'Women-Bags-Briefcases',
    'Women-Bags-Clutches',
    'Women-Bags-Luggage',
    'Women-Bags-Shoulder Bags',
    'Women-Bags-Totes',
    'Women-Accessories-Belts',
    'Women-Accessories-Cases',
    'Women-Accessories-Gloves',
    'Women-Accessories-Hair',
    'Women-Accessories-Hats',
    'Women-Accessories-Scarves',
    'Women-Accessories-Sunglasses',
    'Women-Accessories-Umbrellas',
    'Women-Accessories-Wallets',
    'Women-Accessories-Watches',
    'Women-Jewelry-Bracelets',
    'Women-Jewelry-Brooches',
    'Women-Jewelry-Earrings',
    'Women-Jewelry-Necklaces',
    'Women-Jewelry-Rings',
    'Men-Clothing-Beachwear',
    'Men-Clothing-Coats',
    'Men-Clothing-Jackets',
    'Men-Clothing-Jeans',
    'Men-Clothing-Knitwear',
    'Men-Clothing-Nightwear',
    'Men-Clothing-Pants',
    'Men-Clothing-Shirts',
    'Men-Clothing-Shorts',
    'Men-Clothing-Suits',
    'Men-Clothing-Sweats',
    'Men-Clothing-T-Shirts',
    'Men-Clothing-Underwear',
    'Men-Shoes-Boots',
    'Men-Shoes-Lace-Ups',
    'Men-Shoes-Sandals',
    'Men-Shoes-Slip-Ons',
    'Men-Shoes-Sneakers',
    'Men-Shoes-Bags',
    'Men-Shoes-Backpacks',
    'Men-Shoes-Briefcases',
    'Men-Shoes-Cases',
    'Men-Shoes-Holdalls',
    'Men-Shoes-Luggage',
    'Men-Shoes-Messenger',
    'Men-Accessories-Belts',
    'Men-Accessories-Cufflinks',
    'Men-Accessories-Gloves',
    'Men-Accessories-Hats',
    'Men-Accessories-Scarves',
    'Men-Accessories-Sunglasses',
    'Men-Accessories-Ties',
    'Men-Accessories-Wallets',
    'Men-Accessories-Watches',
    'Men-Jewelry-Bracelets',
    'Men-Jewelry-Necklaces',
    'Men-Jewelry-Rings'
    ]
print len(leaves), "categories"

if __name__ == '__main__':
    nsamples, d = 100, 10
    x = np.random.normal(0, 1, (nsamples, d))
    pdb.set_trace()
